name: '${artifact}'
main: '${group}.${artifact}'

version: '${version}'
api-version: '${minecraft}'
description: '${description}'

authors: [ ryderbelserion ]

folia-supported: true

dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
      join-classpath: true
    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true