name: Snapshot Build

on:
  workflow_dispatch:

  push:
    branches:
      - dev

env:
  version_status: "beta"

jobs:
  build:
    uses: ryderbelserion/ryderbelserion/.github/workflows/build.yml@main

    with:
      branch: dev

    secrets:
      webhook: ${{ secrets.CB_WEBHOOK }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
      hangar_token: ${{ secrets.HANGAR_KEY }}